"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FlaskConical, Loader2 } from "lucide-react";

const SKILLS = [
  { id: "feature-prioritization", label: "Feature Prioritization", file: "feature-prioritization.md", date: "February 2026" },
  { id: "competitive-response", label: "Competitive Response", file: "competitive-response.md", date: "February 2026" },
  { id: "customer-discovery", label: "Customer Discovery", file: "customer-discovery.md", date: "February 2026" },
  { id: "north-star-metrics", label: "North Star Metrics", file: "north-star-metrics.md", date: "February 2026" },
  { id: "user-segmentation", label: "User Segmentation", file: "user-segmentation.md", date: "February 2026" },
];

export default function WorkspacePage() {
  const [activeSkill, setActiveSkill] = useState(SKILLS[0].id);
  const [content, setContent] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (content[activeSkill]) return;
    setLoading(true);
    const skill = SKILLS.find((s) => s.id === activeSkill)!;
    fetch(`/outputs/${skill.file}`)
      .then((r) => r.text())
      .then((text) => {
        setContent((prev) => ({ ...prev, [activeSkill]: text }));
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [activeSkill]);

  const md = content[activeSkill] || "";
  const activeSkillData = SKILLS.find((s) => s.id === activeSkill)!;

  return (
    <div className="flex flex-col h-[calc(100vh-64px)]">
      {/* Header */}
      <div className="flex-shrink-0 space-y-4 pb-4">
        <div>
          <p className="text-sm font-medium text-glean-blue mb-1">Generated Outputs</p>
          <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Decision Workspace</h1>
        </div>

        <div className="bg-white rounded-2xl border border-gray-100 p-4">
          <div className="flex items-start gap-3">
            <FlaskConical size={16} className="text-glean-blue mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-[13px] font-medium text-gray-900">5 PM Skills Executed for Glean</p>
              <p className="text-[12px] text-gray-400 mt-0.5 leading-relaxed">
                Real skill outputs generated by the platform, analyzing Glean's product, market, and competitive position.
              </p>
            </div>
          </div>
        </div>

        {/* Skill tabs */}
        <div className="flex gap-1.5 flex-wrap">
          {SKILLS.map((skill) => (
            <button
              key={skill.id}
              onClick={() => setActiveSkill(skill.id)}
              className={`px-3 py-2 rounded-full text-xs font-medium transition-all duration-200 ${
                activeSkill === skill.id
                  ? "bg-glean-blue text-white"
                  : "text-gray-400 hover:text-gray-600 hover:bg-gray-100"
              }`}
            >
              {skill.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content — scrollable */}
      <div className="flex-1 min-h-0 overflow-y-auto pr-1">
        {loading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 size={20} className="animate-spin text-gray-300" />
          </div>
        ) : (
          <motion.div
            key={activeSkill}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
            className="bg-white rounded-2xl border border-gray-100 p-6 sm:p-8"
          >
            {/* Skill metadata header */}
            <div className="mb-6 pb-5 border-b border-gray-100">
              <h2 className="text-lg font-bold text-gray-900">
                {activeSkillData.label} — Glean
              </h2>
              <div className="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-[12px] text-gray-400">
                <span>
                  Skill: <span className="text-glean-blue font-medium">{activeSkillData.id}</span>
                </span>
                <span className="text-gray-200">|</span>
                <span>Company: <span className="text-gray-600 font-medium">Glean</span> (AI-Powered Enterprise Search & Assistant)</span>
                <span className="text-gray-200">|</span>
                <span>Date: {activeSkillData.date}</span>
              </div>
            </div>

            <MarkdownRenderer content={md} />
          </motion.div>
        )}
      </div>
    </div>
  );
}

function MarkdownRenderer({ content }: { content: string }) {
  const lines = content.split("\n");
  const elements: React.ReactNode[] = [];
  let i = 0;
  let key = 0;

  while (i < lines.length) {
    const line = lines[i];

    // Horizontal rule
    if (line.trim() === "---") {
      elements.push(<hr key={key++} className="my-6 border-gray-100" />);
      i++;
      continue;
    }

    // Table
    if (line.includes("|") && i + 1 < lines.length && lines[i + 1]?.includes("---")) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].includes("|")) {
        tableLines.push(lines[i]);
        i++;
      }
      const headers = tableLines[0].split("|").filter(Boolean).map((h) => h.trim());
      const rows = tableLines.slice(2).map((r) =>
        r.split("|").filter(Boolean).map((c) => c.trim())
      );
      elements.push(
        <div key={key++} className="overflow-x-auto my-4 rounded-xl border border-gray-100">
          <table className="w-full text-[12px]">
            <thead>
              <tr>
                {headers.map((h, j) => (
                  <th key={j} className="bg-gray-50 p-2.5 text-left text-gray-600 font-medium border-b border-gray-100">
                    <span dangerouslySetInnerHTML={{ __html: inlineMd(h) }} />
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, ri) => (
                <tr key={ri} className="border-b border-gray-50">
                  {row.map((cell, ci) => (
                    <td key={ci} className="p-2.5 text-gray-600" dangerouslySetInnerHTML={{ __html: inlineMd(cell) }} />
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
      continue;
    }

    // Code block
    if (line.startsWith("```")) {
      i++;
      const codeLines: string[] = [];
      while (i < lines.length && !lines[i].startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++; // skip closing ```
      elements.push(
        <pre key={key++} className="bg-gray-50 rounded-xl p-4 text-[11px] font-mono overflow-x-auto my-4 leading-relaxed">
          {codeLines.join("\n")}
        </pre>
      );
      continue;
    }

    // Empty line
    if (line.trim() === "") {
      i++;
      continue;
    }

    // Headings
    if (line.startsWith("# ") && !line.startsWith("## ")) {
      elements.push(
        <h1 key={key++} className="text-xl font-bold text-gray-900 mt-2 mb-3">
          {line.slice(2)}
        </h1>
      );
      i++;
      continue;
    }
    if (line.startsWith("## ")) {
      elements.push(
        <h2 key={key++} className="text-lg font-bold text-gray-900 mt-8 mb-3">
          {line.slice(3)}
        </h2>
      );
      i++;
      continue;
    }
    if (line.startsWith("### ")) {
      elements.push(
        <h3 key={key++} className="text-[15px] font-semibold text-gray-800 mt-6 mb-2">
          {line.slice(4)}
        </h3>
      );
      i++;
      continue;
    }
    if (line.startsWith("#### ")) {
      elements.push(
        <h4 key={key++} className="text-[13px] font-semibold text-gray-700 mt-4 mb-1">
          {line.slice(5)}
        </h4>
      );
      i++;
      continue;
    }

    // Blockquote
    if (line.startsWith("> ")) {
      const quoteLines: string[] = [];
      while (i < lines.length && lines[i].startsWith("> ")) {
        quoteLines.push(lines[i].slice(2));
        i++;
      }
      elements.push(
        <blockquote key={key++} className="border-l-2 border-glean-blue/30 pl-4 my-3 text-[13px] text-gray-500 italic">
          <span dangerouslySetInnerHTML={{ __html: inlineMd(quoteLines.join(" ")) }} />
        </blockquote>
      );
      continue;
    }

    // Unordered list items
    if (line.match(/^[-*] /)) {
      const listItems: string[] = [];
      while (i < lines.length && lines[i].match(/^[-*] /)) {
        listItems.push(lines[i].replace(/^[-*] /, ""));
        i++;
      }
      elements.push(
        <ul key={key++} className="my-2 space-y-1">
          {listItems.map((item, li) => (
            <li key={li} className="flex items-start gap-2 text-[13px] text-gray-600 leading-relaxed">
              <span className="text-gray-300 mt-1.5 flex-shrink-0">&#x2022;</span>
              <span dangerouslySetInnerHTML={{ __html: inlineMd(item) }} />
            </li>
          ))}
        </ul>
      );
      continue;
    }

    // Numbered list
    if (line.match(/^\d+\. /)) {
      const listItems: string[] = [];
      while (i < lines.length && lines[i].match(/^\d+\. /)) {
        listItems.push(lines[i].replace(/^\d+\. /, ""));
        i++;
      }
      elements.push(
        <ol key={key++} className="my-2 space-y-1">
          {listItems.map((item, li) => (
            <li key={li} className="flex items-start gap-2 text-[13px] text-gray-600 leading-relaxed">
              <span className="text-gray-400 font-medium flex-shrink-0 w-4 text-right">{li + 1}.</span>
              <span dangerouslySetInnerHTML={{ __html: inlineMd(item) }} />
            </li>
          ))}
        </ol>
      );
      continue;
    }

    // Regular paragraph
    elements.push(
      <p key={key++} className="text-[13px] text-gray-600 leading-relaxed my-2" dangerouslySetInnerHTML={{ __html: inlineMd(line) }} />
    );
    i++;
  }

  return <div className="max-w-none">{elements}</div>;
}

function inlineMd(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-gray-800 font-semibold">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code class="bg-gray-100 px-1.5 py-0.5 rounded text-[11px] font-mono text-gray-700">$1</code>')
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2" class="text-glean-blue hover:underline" target="_blank" rel="noopener">$1</a>');
}
